#Tampilan menu utama
print ("✨ Current Level ✨")
print ("💰 XP Saat ini")
print ("🙍‍♀️ Profil")
print ("📅 Kalendar")
print ("🎠 Level 1")
print ("🎠 Level 2")
print ("🎠 Level 3")
print ("🎠 Level 4")
print ("🎠 Level 5")
print ("🎇 Level 6")
print ("🎇 Level 7")
print ("🥉 Level 8")
print ("🥈 Level 9")
print ("🥇 Level 10")
print ("🎁 Surprise Day 🎁")