#Tampilan di dalam level
print ("Level 1")
print ("    Tercapai or Tidak Tercapai")
print ("Level 2")
print ("    Tercapai or Tidak Tercapai")
print ("Level 3")
print ("    Tercapai or Tidak Tercapai")
print ("Level 4")
print ("    Tercapai or Tidak Tercapai")
print ("Level 5")
print ("    Tercapai or Tidak Tercapai")
print ("Level 6")
print ("    Tercapai or Tidak Tercapai")
print ("Level 7")
print ("    Tercapai or Tidak Tercapai")
print ("Level 8")
print ("    Tercapai or Tidak Tercapai")
print ("Level 9")
print ("    Tercapai or Tidak Tercapai")
print ("Level 10")
print ("    Tercapai or Tidak Tercapai")